### ISSUE TITLE
Not available on HACS

### ISSUE THREAD

**Issue by DanielHoelder** [Mariusthvdb/custom-icon-color#10]
Hi,
I can't find the module on HACS. Search for "custom-icon-color" produces no result. 
Was the addon deleted from HACS?

**Comment by Mariusthvdb** [comment]
as with HACS custom repositories:
add the repo url to the HACS custom downloader

<img width="371" alt="Scherm­afbeelding 2024-08-09 om 16 19 55" src="https://github.com/user-attachments/assets/d5d3906e-d384-4bad-8097-6703e92ae15c">

and find it in the HACS overview after that:

<img width="939" alt="Scherm­afbeelding 2024-08-09 om 16 20 51" src="https://github.com/user-attachments/assets/b7dc2b20-2c57-4870-b72a-90e1bf7ffa76">

**Comment by DanielHoelder** [comment]
Ok, thanks.
