### ISSUE TITLE
Error to add hack

### ISSUE THREAD

**Issue by budswarez** [Mariusthvdb/custom-icon-color#5]
Repository Mariusthvdb/custom-ui-icon-color not found

![image](https://github.com/Mariusthvdb/custom-icon-color/assets/7081496/c207378e-327e-4d0b-940e-0681c3a31e5e)

![image](https://github.com/Mariusthvdb/custom-icon-color/assets/7081496/cf90c1fd-8546-4a1b-abfe-cbd2e7a34e2e)

**Comment by Mariusthvdb** [comment]
Use custom-icon-color please

**Comment by budswarez** [comment]
> Use custom-icon-color please

Link is incorrect?
![image](https://github.com/Mariusthvdb/custom-icon-color/assets/7081496/08a46106-7686-42b9-8da0-e863c785daca)

**Comment by Mariusthvdb** [comment]
Thanks for reporting. I missed that during the name change. Will fix.
