### ISSUE TITLE
Error with Re-use mods system wide

### ISSUE THREAD

**Issue by zephyroff-hosting** [Mariusthvdb/custom-icon-color#7]
Hi,
I have a problem with the tip given here (https://github.com/Mariusthvdb/custom-icon-color/blob/main/CARD-MOD-EXAMPLES.md#re-use-mods-system-wide) to use the !secret as a template.
I have done everything noted in the note but I have a tag error.

![image](https://github.com/Mariusthvdb/custom-icon-color/assets/150131559/506a4038-6368-4329-b029-af3c034b808b)

While my secret file is full
![image](https://github.com/Mariusthvdb/custom-icon-color/assets/150131559/5180a512-26a9-407b-be6f-9417b01c7726)

Do you have any idea of the source of the problem?

**Comment by Mariusthvdb** [comment]
Yes you can not use those in the Ui editor, only in yaml mode

**Comment by zephyroff-hosting** [comment]
Yes but in yaml mode, I have this message

![image](https://github.com/Mariusthvdb/custom-icon-color/assets/150131559/8f41ba88-c584-4af6-9283-bf2809db57f9)

**Comment by zephyroff-hosting** [comment]
Maybe you have another idea for create a template of icon_color ?

**Comment by zephyroff-hosting** [comment]
Ok I found my problem
